package s0.a.a.q2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface c {
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i = new n("1.3.6.1.4.1.188.7.1.1.2");
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y = new n("1.3.6.1.4.1.11591.4.11");
    public static final n z = new n("1.3.6.1.4.1.18227.2.1");

    static {
        n nVar = new n("2.16.840.1.113730.1");
        a = nVar;
        Objects.requireNonNull(nVar);
        b = new n(nVar, "1");
        Objects.requireNonNull(nVar);
        new n(nVar, "2");
        Objects.requireNonNull(nVar);
        c = new n(nVar, "3");
        Objects.requireNonNull(nVar);
        new n(nVar, "4");
        Objects.requireNonNull(nVar);
        new n(nVar, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar);
        new n(nVar, "8");
        Objects.requireNonNull(nVar);
        new n(nVar, "12");
        Objects.requireNonNull(nVar);
        new n(nVar, "13");
        n nVar2 = new n("2.16.840.1.113733.1");
        d = nVar2;
        Objects.requireNonNull(nVar2);
        e = new n(nVar2, "6.3");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "6.9");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "6.11");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "6.13");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "6.15");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "8.1");
        n nVar3 = new n("2.16.840.1.113719");
        f = nVar3;
        Objects.requireNonNull(nVar3);
        new n(nVar3, "1.9.4.1");
        n nVar4 = new n("1.2.840.113533.7");
        g = nVar4;
        Objects.requireNonNull(nVar4);
        new n(nVar4, "65.0");
        Objects.requireNonNull(nVar4);
        h = new n(nVar4, "66.10");
        new n("1.3.6.1.5.5.8.1.2");
        n nVar5 = new n("1.3.6.1.4.1.3029");
        j = nVar5;
        Objects.requireNonNull(nVar5);
        n nVar6 = new n(nVar5, "1");
        k = nVar6;
        Objects.requireNonNull(nVar6);
        l = new n(nVar6, "1.1");
        Objects.requireNonNull(nVar6);
        m = new n(nVar6, "1.2");
        Objects.requireNonNull(nVar6);
        n = new n(nVar6, "1.3");
        Objects.requireNonNull(nVar6);
        o = new n(nVar6, "1.4");
        n nVar7 = new n("1.3.6.1.4.1.1722.12.2");
        p = nVar7;
        Objects.requireNonNull(nVar7);
        q = new n(nVar7, "1.5");
        Objects.requireNonNull(nVar7);
        r = new n(nVar7, "1.8");
        Objects.requireNonNull(nVar7);
        s = new n(nVar7, "1.12");
        Objects.requireNonNull(nVar7);
        t = new n(nVar7, "1.16");
        Objects.requireNonNull(nVar7);
        u = new n(nVar7, "2.4");
        Objects.requireNonNull(nVar7);
        v = new n(nVar7, "2.5");
        Objects.requireNonNull(nVar7);
        w = new n(nVar7, "2.7");
        Objects.requireNonNull(nVar7);
        x = new n(nVar7, "2.8");
    }
}
