package s0.a.a.c2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface a {
    public static final n A;
    public static final n B;
    public static final n C;
    public static final n D;
    public static final n E;
    public static final n F;
    public static final n G;
    public static final n H;
    public static final n I;
    public static final n J;
    public static final n K;
    public static final n L;
    public static final n M;
    public static final n N;
    public static final n O;
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.3.6.1.4.1.22554");
        a = nVar;
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "1");
        b = nVar2;
        Objects.requireNonNull(nVar2);
        n nVar3 = new n(nVar2, "1");
        c = nVar3;
        Objects.requireNonNull(nVar2);
        n nVar4 = new n(nVar2, "2.1");
        d = nVar4;
        Objects.requireNonNull(nVar2);
        new n(nVar2, "2.2");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "2.3");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "2.4");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "1");
        Objects.requireNonNull(nVar3);
        n nVar5 = new n(nVar3, "2");
        e = nVar5;
        Objects.requireNonNull(nVar4);
        new n(nVar4, "1");
        Objects.requireNonNull(nVar4);
        n nVar6 = new n(nVar4, "2");
        f = nVar6;
        Objects.requireNonNull(nVar5);
        g = new n(nVar5, "1.2");
        Objects.requireNonNull(nVar5);
        h = new n(nVar5, "1.22");
        Objects.requireNonNull(nVar5);
        i = new n(nVar5, "1.42");
        Objects.requireNonNull(nVar6);
        j = new n(nVar6, "1.2");
        Objects.requireNonNull(nVar6);
        k = new n(nVar6, "1.22");
        Objects.requireNonNull(nVar6);
        l = new n(nVar6, "1.42");
        Objects.requireNonNull(nVar);
        n nVar7 = new n(nVar, "2");
        m = nVar7;
        Objects.requireNonNull(nVar7);
        n nVar8 = new n(nVar7, "1");
        n = nVar8;
        Objects.requireNonNull(nVar8);
        o = new n(nVar8, "1");
        Objects.requireNonNull(nVar8);
        p = new n(nVar8, "2");
        Objects.requireNonNull(nVar8);
        q = new n(nVar8, "3");
        Objects.requireNonNull(nVar7);
        n nVar9 = new n(nVar7, "2");
        r = nVar9;
        Objects.requireNonNull(nVar9);
        s = new n(nVar9, "1");
        Objects.requireNonNull(nVar9);
        t = new n(nVar9, "2");
        Objects.requireNonNull(nVar9);
        u = new n(nVar9, "3");
        Objects.requireNonNull(nVar9);
        v = new n(nVar9, "4");
        Objects.requireNonNull(nVar9);
        w = new n(nVar9, "5");
        Objects.requireNonNull(nVar9);
        x = new n(nVar9, "6");
        Objects.requireNonNull(nVar9);
        y = new n(nVar9, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar9);
        z = new n(nVar9, "8");
        Objects.requireNonNull(nVar7);
        n nVar10 = new n(nVar7, "3");
        A = nVar10;
        Objects.requireNonNull(nVar10);
        B = new n(nVar10, "1");
        Objects.requireNonNull(nVar10);
        C = new n(nVar10, "2");
        Objects.requireNonNull(nVar10);
        D = new n(nVar10, "3");
        Objects.requireNonNull(nVar10);
        E = new n(nVar10, "4");
        Objects.requireNonNull(nVar10);
        F = new n(nVar10, "5");
        Objects.requireNonNull(nVar10);
        G = new n(nVar10, "6");
        Objects.requireNonNull(nVar10);
        H = new n(nVar10, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar10);
        I = new n(nVar10, "8");
        Objects.requireNonNull(nVar7);
        n nVar11 = new n(nVar7, "4");
        J = nVar11;
        Objects.requireNonNull(nVar11);
        new n(nVar11, "1");
        Objects.requireNonNull(nVar11);
        new n(nVar11, "2");
        Objects.requireNonNull(nVar11);
        new n(nVar11, "3");
        Objects.requireNonNull(nVar11);
        new n(nVar11, "4");
        Objects.requireNonNull(nVar11);
        new n(nVar11, "5");
        Objects.requireNonNull(nVar11);
        K = new n(nVar11, "11");
        Objects.requireNonNull(nVar11);
        L = new n(nVar11, "12");
        Objects.requireNonNull(nVar);
        n nVar12 = new n(nVar, "3");
        M = nVar12;
        Objects.requireNonNull(nVar12);
        N = new n(nVar12, "1");
        Objects.requireNonNull(nVar);
        n nVar13 = new n(nVar, "4");
        O = nVar13;
        Objects.requireNonNull(nVar13);
        new n(nVar13, "1");
    }
}
