package m0.r.t.a.r.e.a.u;

import kotlin.reflect.jvm.internal.impl.builtins.ReflectionTypes;
import kotlin.reflect.jvm.internal.impl.load.java.AnnotationTypeQualifierResolver;
import kotlin.reflect.jvm.internal.impl.load.java.typeEnhancement.SignatureEnhancement;
import kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializedDescriptorResolver;
import m0.r.t.a.r.c.k0;
import m0.r.t.a.r.c.u;
import m0.r.t.a.r.e.a.i;
import m0.r.t.a.r.e.a.j;
import m0.r.t.a.r.e.a.s.c;
import m0.r.t.a.r.e.a.s.d;
import m0.r.t.a.r.e.a.s.e;
import m0.r.t.a.r.e.a.v.b;
import m0.r.t.a.r.e.b.o;
import m0.r.t.a.r.l.l;
import m0.r.t.a.r.m.x0.h;
import m0.r.t.a.r.o.g;

/* compiled from: context.kt */
public final class a {
    public final l a;
    public final i b;
    public final m0.r.t.a.r.e.b.i c;
    public final DeserializedDescriptorResolver d;
    public final e e;
    public final m0.r.t.a.r.k.b.l f;
    public final d g;
    public final c h;
    public final m0.r.t.a.r.j.t.a i;
    public final b j;
    public final d k;
    public final o l;
    public final k0 m;
    public final m0.r.t.a.r.d.a.c n;
    public final u o;
    public final ReflectionTypes p;
    public final AnnotationTypeQualifierResolver q;
    public final SignatureEnhancement r;
    public final j s;
    public final b t;
    public final h u;
    public final g v;

    public a(l lVar, i iVar, m0.r.t.a.r.e.b.i iVar2, DeserializedDescriptorResolver deserializedDescriptorResolver, e eVar, m0.r.t.a.r.k.b.l lVar2, d dVar, c cVar, m0.r.t.a.r.j.t.a aVar, b bVar, d dVar2, o oVar, k0 k0Var, m0.r.t.a.r.d.a.c cVar2, u uVar, ReflectionTypes reflectionTypes, AnnotationTypeQualifierResolver annotationTypeQualifierResolver, SignatureEnhancement signatureEnhancement, j jVar, b bVar2, h hVar, g gVar) {
        l lVar3 = lVar;
        i iVar3 = iVar;
        m0.r.t.a.r.e.b.i iVar4 = iVar2;
        DeserializedDescriptorResolver deserializedDescriptorResolver2 = deserializedDescriptorResolver;
        e eVar2 = eVar;
        m0.r.t.a.r.k.b.l lVar4 = lVar2;
        d dVar3 = dVar;
        c cVar3 = cVar;
        m0.r.t.a.r.j.t.a aVar2 = aVar;
        b bVar3 = bVar;
        d dVar4 = dVar2;
        o oVar2 = oVar;
        k0 k0Var2 = k0Var;
        m0.r.t.a.r.d.a.c cVar4 = cVar2;
        ReflectionTypes reflectionTypes2 = reflectionTypes;
        m0.n.b.i.e(lVar3, "storageManager");
        m0.n.b.i.e(iVar3, "finder");
        m0.n.b.i.e(iVar4, "kotlinClassFinder");
        m0.n.b.i.e(deserializedDescriptorResolver2, "deserializedDescriptorResolver");
        m0.n.b.i.e(eVar2, "signaturePropagator");
        m0.n.b.i.e(lVar4, "errorReporter");
        m0.n.b.i.e(dVar3, "javaResolverCache");
        m0.n.b.i.e(cVar3, "javaPropertyInitializerEvaluator");
        m0.n.b.i.e(aVar2, "samConversionResolver");
        m0.n.b.i.e(bVar3, "sourceElementFactory");
        m0.n.b.i.e(dVar4, "moduleClassResolver");
        m0.n.b.i.e(oVar2, "packagePartProvider");
        m0.n.b.i.e(k0Var2, "supertypeLoopChecker");
        m0.n.b.i.e(cVar4, "lookupTracker");
        m0.n.b.i.e(uVar, "module");
        m0.n.b.i.e(reflectionTypes, "reflectionTypes");
        m0.n.b.i.e(annotationTypeQualifierResolver, "annotationTypeQualifierResolver");
        m0.n.b.i.e(signatureEnhancement, "signatureEnhancement");
        m0.n.b.i.e(jVar, "javaClassesTracker");
        m0.n.b.i.e(bVar2, "settings");
        m0.n.b.i.e(hVar, "kotlinTypeChecker");
        m0.n.b.i.e(gVar, "javaTypeEnhancementState");
        this.a = lVar3;
        this.b = iVar3;
        this.c = iVar4;
        this.d = deserializedDescriptorResolver2;
        this.e = eVar2;
        this.f = lVar4;
        this.g = dVar3;
        this.h = cVar3;
        this.i = aVar2;
        this.j = bVar3;
        this.k = dVar4;
        this.l = oVar2;
        this.m = k0Var2;
        this.n = cVar4;
        this.o = uVar;
        this.p = reflectionTypes;
        this.q = annotationTypeQualifierResolver;
        this.r = signatureEnhancement;
        this.s = jVar;
        this.t = bVar2;
        this.u = hVar;
        this.v = gVar;
    }
}
