package s0.a.a.z2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface b {
    public static final n A;
    public static final n B;
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.3.36.3");
        a = nVar;
        Objects.requireNonNull(nVar);
        b = new n(nVar, "2.1");
        Objects.requireNonNull(nVar);
        c = new n(nVar, "2.2");
        Objects.requireNonNull(nVar);
        d = new n(nVar, "2.3");
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "3.1");
        e = nVar2;
        Objects.requireNonNull(nVar2);
        f = new n(nVar2, "2");
        Objects.requireNonNull(nVar2);
        g = new n(nVar2, "3");
        Objects.requireNonNull(nVar2);
        h = new n(nVar2, "4");
        Objects.requireNonNull(nVar);
        n nVar3 = new n(nVar, "3.2");
        i = nVar3;
        Objects.requireNonNull(nVar3);
        j = new n(nVar3, "1");
        Objects.requireNonNull(nVar3);
        k = new n(nVar3, "2");
        Objects.requireNonNull(nVar);
        n nVar4 = new n(nVar, "3.2.8");
        l = nVar4;
        Objects.requireNonNull(nVar4);
        n nVar5 = new n(nVar4, "1");
        m = nVar5;
        Objects.requireNonNull(nVar5);
        n nVar6 = new n(nVar5, "1");
        n = nVar6;
        Objects.requireNonNull(nVar6);
        o = new n(nVar6, "1");
        Objects.requireNonNull(nVar6);
        p = new n(nVar6, "2");
        Objects.requireNonNull(nVar6);
        q = new n(nVar6, "3");
        Objects.requireNonNull(nVar6);
        r = new n(nVar6, "4");
        Objects.requireNonNull(nVar6);
        s = new n(nVar6, "5");
        Objects.requireNonNull(nVar6);
        t = new n(nVar6, "6");
        Objects.requireNonNull(nVar6);
        u = new n(nVar6, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar6);
        v = new n(nVar6, "8");
        Objects.requireNonNull(nVar6);
        w = new n(nVar6, "9");
        Objects.requireNonNull(nVar6);
        x = new n(nVar6, "10");
        Objects.requireNonNull(nVar6);
        y = new n(nVar6, "11");
        Objects.requireNonNull(nVar6);
        z = new n(nVar6, "12");
        Objects.requireNonNull(nVar6);
        A = new n(nVar6, "13");
        Objects.requireNonNull(nVar6);
        B = new n(nVar6, "14");
    }
}
