package s0.a.a.r2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface b {
    public static final n A;
    public static final n B;
    public static final n C;
    public static final n D;
    public static final n E;
    public static final n F;
    public static final n G;
    public static final n H;
    public static final n I;
    public static final n J;
    public static final n K;
    public static final n L;
    public static final n M;
    public static final n N;
    public static final n O;
    public static final n P;
    public static final n Q;
    public static final n R;
    public static final n S;
    public static final n T;
    public static final n U;
    public static final n V;
    public static final n W;
    public static final n X;
    public static final n Y;
    public static final n Z;
    public static final n a;
    public static final n a0;
    public static final n b;
    public static final n b0;
    public static final n c;
    public static final n c0;
    public static final n d;
    public static final n d0;
    public static final n e;
    public static final n e0;
    public static final n f;
    public static final n f0;
    public static final n g;

    /* renamed from: g0  reason: collision with root package name */
    public static final n f52g0;
    public static final n h;

    /* renamed from: h0  reason: collision with root package name */
    public static final n f53h0;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("2.16.840.1.101.3.4");
        a = nVar;
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "2");
        b = nVar2;
        Objects.requireNonNull(nVar2);
        c = new n(nVar2, "1");
        Objects.requireNonNull(nVar2);
        d = new n(nVar2, "2");
        Objects.requireNonNull(nVar2);
        e = new n(nVar2, "3");
        Objects.requireNonNull(nVar2);
        f = new n(nVar2, "4");
        Objects.requireNonNull(nVar2);
        g = new n(nVar2, "5");
        Objects.requireNonNull(nVar2);
        h = new n(nVar2, "6");
        Objects.requireNonNull(nVar2);
        i = new n(nVar2, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar2);
        j = new n(nVar2, "8");
        Objects.requireNonNull(nVar2);
        k = new n(nVar2, "9");
        Objects.requireNonNull(nVar2);
        l = new n(nVar2, "10");
        Objects.requireNonNull(nVar2);
        m = new n(nVar2, "11");
        Objects.requireNonNull(nVar2);
        n = new n(nVar2, "12");
        Objects.requireNonNull(nVar2);
        o = new n(nVar2, "13");
        Objects.requireNonNull(nVar2);
        p = new n(nVar2, "14");
        Objects.requireNonNull(nVar2);
        q = new n(nVar2, "15");
        Objects.requireNonNull(nVar2);
        r = new n(nVar2, "16");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "17");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "18");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "19");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "20");
        Objects.requireNonNull(nVar);
        n nVar3 = new n(nVar, "1");
        s = nVar3;
        Objects.requireNonNull(nVar3);
        t = new n(nVar3, "1");
        Objects.requireNonNull(nVar3);
        u = new n(nVar3, "2");
        Objects.requireNonNull(nVar3);
        v = new n(nVar3, "3");
        Objects.requireNonNull(nVar3);
        w = new n(nVar3, "4");
        Objects.requireNonNull(nVar3);
        x = new n(nVar3, "5");
        Objects.requireNonNull(nVar3);
        y = new n(nVar3, "6");
        Objects.requireNonNull(nVar3);
        z = new n(nVar3, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar3);
        A = new n(nVar3, "8");
        Objects.requireNonNull(nVar3);
        B = new n(nVar3, "21");
        Objects.requireNonNull(nVar3);
        C = new n(nVar3, "22");
        Objects.requireNonNull(nVar3);
        D = new n(nVar3, "23");
        Objects.requireNonNull(nVar3);
        E = new n(nVar3, "24");
        Objects.requireNonNull(nVar3);
        F = new n(nVar3, "25");
        Objects.requireNonNull(nVar3);
        G = new n(nVar3, "26");
        Objects.requireNonNull(nVar3);
        H = new n(nVar3, "27");
        Objects.requireNonNull(nVar3);
        I = new n(nVar3, "28");
        Objects.requireNonNull(nVar3);
        J = new n(nVar3, "41");
        Objects.requireNonNull(nVar3);
        K = new n(nVar3, "42");
        Objects.requireNonNull(nVar3);
        L = new n(nVar3, "43");
        Objects.requireNonNull(nVar3);
        M = new n(nVar3, "44");
        Objects.requireNonNull(nVar3);
        N = new n(nVar3, "45");
        Objects.requireNonNull(nVar3);
        O = new n(nVar3, "46");
        Objects.requireNonNull(nVar3);
        P = new n(nVar3, "47");
        Objects.requireNonNull(nVar3);
        Q = new n(nVar3, "48");
        Objects.requireNonNull(nVar);
        n nVar4 = new n(nVar, "3");
        R = nVar4;
        Objects.requireNonNull(nVar4);
        S = new n(nVar4, "1");
        Objects.requireNonNull(nVar4);
        T = new n(nVar4, "2");
        Objects.requireNonNull(nVar4);
        U = new n(nVar4, "3");
        Objects.requireNonNull(nVar4);
        V = new n(nVar4, "4");
        Objects.requireNonNull(nVar4);
        W = new n(nVar4, "5");
        Objects.requireNonNull(nVar4);
        X = new n(nVar4, "6");
        Objects.requireNonNull(nVar4);
        Y = new n(nVar4, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar4);
        Z = new n(nVar4, "8");
        Objects.requireNonNull(nVar4);
        a0 = new n(nVar4, "9");
        Objects.requireNonNull(nVar4);
        b0 = new n(nVar4, "10");
        Objects.requireNonNull(nVar4);
        c0 = new n(nVar4, "11");
        Objects.requireNonNull(nVar4);
        d0 = new n(nVar4, "12");
        Objects.requireNonNull(nVar4);
        e0 = new n(nVar4, "13");
        Objects.requireNonNull(nVar4);
        f0 = new n(nVar4, "14");
        Objects.requireNonNull(nVar4);
        f52g0 = new n(nVar4, "15");
        Objects.requireNonNull(nVar4);
        f53h0 = new n(nVar4, "16");
    }
}
