package s0.a.a.y2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.d3.m;
import s0.a.a.n;

public interface d {
    public static final n A;
    public static final n B;
    public static final n C;
    public static final n D;
    public static final n E;
    public static final n F;
    public static final n G = m.G1;
    public static final n H = m.M1;
    public static final n I;
    public static final n J;
    public static final n K;
    public static final n L;
    public static final n M;
    public static final n N;
    public static final n O;
    public static final n P;
    public static final n Q;
    public static final n R;
    public static final n S;
    public static final n T;
    public static final n U;
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.3.132.0");
        a = nVar;
        Objects.requireNonNull(nVar);
        b = new n(nVar, "1");
        Objects.requireNonNull(nVar);
        c = new n(nVar, "2");
        Objects.requireNonNull(nVar);
        d = new n(nVar, "3");
        Objects.requireNonNull(nVar);
        e = new n(nVar, "4");
        Objects.requireNonNull(nVar);
        f = new n(nVar, "5");
        Objects.requireNonNull(nVar);
        g = new n(nVar, "6");
        Objects.requireNonNull(nVar);
        h = new n(nVar, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar);
        i = new n(nVar, "8");
        Objects.requireNonNull(nVar);
        j = new n(nVar, "9");
        Objects.requireNonNull(nVar);
        k = new n(nVar, "10");
        Objects.requireNonNull(nVar);
        l = new n(nVar, "15");
        Objects.requireNonNull(nVar);
        m = new n(nVar, "16");
        Objects.requireNonNull(nVar);
        n = new n(nVar, "17");
        Objects.requireNonNull(nVar);
        o = new n(nVar, "22");
        Objects.requireNonNull(nVar);
        p = new n(nVar, "23");
        Objects.requireNonNull(nVar);
        q = new n(nVar, "24");
        Objects.requireNonNull(nVar);
        r = new n(nVar, "25");
        Objects.requireNonNull(nVar);
        s = new n(nVar, "26");
        Objects.requireNonNull(nVar);
        t = new n(nVar, "27");
        Objects.requireNonNull(nVar);
        u = new n(nVar, "28");
        Objects.requireNonNull(nVar);
        v = new n(nVar, "29");
        Objects.requireNonNull(nVar);
        w = new n(nVar, "30");
        Objects.requireNonNull(nVar);
        x = new n(nVar, "31");
        Objects.requireNonNull(nVar);
        y = new n(nVar, "32");
        Objects.requireNonNull(nVar);
        z = new n(nVar, "33");
        Objects.requireNonNull(nVar);
        A = new n(nVar, "34");
        Objects.requireNonNull(nVar);
        B = new n(nVar, "35");
        Objects.requireNonNull(nVar);
        C = new n(nVar, "36");
        Objects.requireNonNull(nVar);
        D = new n(nVar, "37");
        Objects.requireNonNull(nVar);
        E = new n(nVar, "38");
        Objects.requireNonNull(nVar);
        F = new n(nVar, "39");
        n nVar2 = new n("1.3.132.1");
        I = nVar2;
        Objects.requireNonNull(nVar2);
        J = new n(nVar2, "11.0");
        Objects.requireNonNull(nVar2);
        K = new n(nVar2, "11.1");
        Objects.requireNonNull(nVar2);
        L = new n(nVar2, "11.2");
        Objects.requireNonNull(nVar2);
        M = new n(nVar2, "11.3");
        Objects.requireNonNull(nVar2);
        N = new n(nVar2, "14.0");
        Objects.requireNonNull(nVar2);
        O = new n(nVar2, "14.1");
        Objects.requireNonNull(nVar2);
        P = new n(nVar2, "14.2");
        Objects.requireNonNull(nVar2);
        Q = new n(nVar2, "14.3");
        Objects.requireNonNull(nVar2);
        R = new n(nVar2, "15.0");
        Objects.requireNonNull(nVar2);
        S = new n(nVar2, "15.1");
        Objects.requireNonNull(nVar2);
        T = new n(nVar2, "15.2");
        Objects.requireNonNull(nVar2);
        U = new n(nVar2, "15.3");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "16.0");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "16.1");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "16.2");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "16.3");
    }
}
