package s0.a.a.j2;

import java.util.Objects;
import s0.a.a.n;

public interface b {
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;

    static {
        n nVar = new n("1.2.156.10197.1");
        a = nVar;
        Objects.requireNonNull(nVar);
        new n(nVar, "101.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "101.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "101.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "101.4");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.4");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.5");
        Objects.requireNonNull(nVar);
        new n(nVar, "102.6");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.4");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.5");
        Objects.requireNonNull(nVar);
        new n(nVar, "103.6");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.4");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.5");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.6");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.7");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.8");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.9");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.10");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.11");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.12");
        Objects.requireNonNull(nVar);
        new n(nVar, "104.100");
        Objects.requireNonNull(nVar);
        new n(nVar, "201");
        Objects.requireNonNull(nVar);
        b = new n(nVar, "301");
        Objects.requireNonNull(nVar);
        new n(nVar, "301.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "301.2");
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "301.3");
        c = nVar2;
        Objects.requireNonNull(nVar);
        d = new n(nVar, "301.101");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "1");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "2");
        Objects.requireNonNull(nVar2);
        e = new n(nVar2, "2.1");
        Objects.requireNonNull(nVar2);
        f = new n(nVar2, "2.2");
        Objects.requireNonNull(nVar2);
        g = new n(nVar2, "2.3");
        Objects.requireNonNull(nVar2);
        h = new n(nVar2, "2.4");
        Objects.requireNonNull(nVar2);
        i = new n(nVar2, "2.5");
        Objects.requireNonNull(nVar2);
        j = new n(nVar2, "2.6");
        Objects.requireNonNull(nVar2);
        k = new n(nVar2, "2.7");
        Objects.requireNonNull(nVar2);
        l = new n(nVar2, "2.8");
        Objects.requireNonNull(nVar2);
        m = new n(nVar2, "2.9");
        Objects.requireNonNull(nVar2);
        n = new n(nVar2, "2.10");
        Objects.requireNonNull(nVar2);
        o = new n(nVar2, "2.11");
        Objects.requireNonNull(nVar);
        new n(nVar, "302");
        Objects.requireNonNull(nVar);
        new n(nVar, "302.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "302.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "302.3");
        Objects.requireNonNull(nVar);
        n nVar3 = new n(nVar, "401");
        p = nVar3;
        Objects.requireNonNull(nVar3);
        q = new n(nVar3, "2");
        Objects.requireNonNull(nVar);
        r = new n(nVar, "501");
        Objects.requireNonNull(nVar);
        new n(nVar, "502");
        Objects.requireNonNull(nVar);
        s = new n(nVar, "503");
        Objects.requireNonNull(nVar);
        new n(nVar, "504");
        Objects.requireNonNull(nVar);
        new n(nVar, "505");
        Objects.requireNonNull(nVar);
        new n(nVar, "506");
        Objects.requireNonNull(nVar);
        new n(nVar, "507");
        Objects.requireNonNull(nVar);
        new n(nVar, "520");
        Objects.requireNonNull(nVar);
        new n(nVar, "521");
        Objects.requireNonNull(nVar);
        new n(nVar, "522");
    }
}
