package s0.a.a.b3.e;

import com.instabug.library.internal.storage.cache.db.InstabugDbContract;
import i0.d.a.a.a;
import java.util.Hashtable;
import s0.a.a.a1;
import s0.a.a.b3.b;
import s0.a.a.b3.c;
import s0.a.a.e;
import s0.a.a.f1;
import s0.a.a.n;
import s0.a.a.u0;

public class d extends a {
    public static final n A;
    public static final n B;
    public static final n C;
    public static final n D;
    public static final n E;
    public static final n F;
    public static final n G;
    public static final n H;
    public static final n I;
    public static final n J;
    public static final n K;
    public static final n L;
    public static final n M;
    public static final n N;
    public static final n O;
    public static final n P;
    public static final n Q;
    public static final Hashtable R;
    public static final Hashtable S;
    public static final s0.a.a.b3.d T = new d();
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;
    public final Hashtable U = a.e(S);
    public final Hashtable V = a.e(R);

    static {
        n q1 = a.q1("2.5.4.15");
        a = q1;
        n q12 = a.q1("2.5.4.6");
        b = q12;
        n q13 = a.q1("2.5.4.3");
        c = q13;
        n q14 = a.q1("0.9.2342.19200300.100.1.25");
        d = q14;
        n q15 = a.q1("2.5.4.13");
        e = q15;
        n q16 = a.q1("2.5.4.27");
        f = q16;
        n q17 = a.q1("2.5.4.49");
        g = q17;
        n q18 = a.q1("2.5.4.46");
        h = q18;
        n q19 = a.q1("2.5.4.47");
        i = q19;
        n q110 = a.q1("2.5.4.23");
        j = q110;
        n q111 = a.q1("2.5.4.44");
        k = q111;
        n q112 = a.q1("2.5.4.42");
        l = q112;
        n q113 = a.q1("2.5.4.51");
        m = q113;
        n q114 = a.q1("2.5.4.43");
        n = q114;
        n q115 = a.q1("2.5.4.25");
        o = q115;
        n q116 = a.q1("2.5.4.7");
        p = q116;
        n nVar = q116;
        n q117 = a.q1("2.5.4.31");
        q = q117;
        n nVar2 = q117;
        n q118 = a.q1("2.5.4.41");
        r = q118;
        n nVar3 = q118;
        n q119 = a.q1("2.5.4.10");
        s = q119;
        n nVar4 = q119;
        n q120 = a.q1("2.5.4.11");
        t = q120;
        n nVar5 = q120;
        n q121 = a.q1("2.5.4.32");
        u = q121;
        n nVar6 = q121;
        n q122 = a.q1("2.5.4.19");
        v = q122;
        n nVar7 = q122;
        n q123 = a.q1("2.5.4.16");
        w = q123;
        n nVar8 = q123;
        n q124 = a.q1("2.5.4.17");
        x = q124;
        n nVar9 = q124;
        n q125 = a.q1("2.5.4.18");
        y = q125;
        n nVar10 = q125;
        n q126 = a.q1("2.5.4.28");
        z = q126;
        n nVar11 = q126;
        n q127 = a.q1("2.5.4.26");
        A = q127;
        n nVar12 = q127;
        n q128 = a.q1("2.5.4.33");
        B = q128;
        n nVar13 = q128;
        n q129 = a.q1("2.5.4.14");
        C = q129;
        n nVar14 = q129;
        n q130 = a.q1("2.5.4.34");
        D = q130;
        n nVar15 = q130;
        n q131 = a.q1("2.5.4.5");
        E = q131;
        n nVar16 = q131;
        n q132 = a.q1("2.5.4.4");
        F = q132;
        n nVar17 = q132;
        n q133 = a.q1("2.5.4.8");
        G = q133;
        n nVar18 = q133;
        n q134 = a.q1("2.5.4.9");
        H = q134;
        n nVar19 = q134;
        n q135 = a.q1("2.5.4.20");
        I = q135;
        n nVar20 = q135;
        n q136 = a.q1("2.5.4.22");
        J = q136;
        n nVar21 = q136;
        n q137 = a.q1("2.5.4.21");
        K = q137;
        n nVar22 = q137;
        n q138 = a.q1("2.5.4.12");
        L = q138;
        n nVar23 = q138;
        n q139 = a.q1("0.9.2342.19200300.100.1.1");
        M = q139;
        n nVar24 = q139;
        n q140 = a.q1("2.5.4.50");
        N = q140;
        n nVar25 = q140;
        n q141 = a.q1("2.5.4.35");
        O = q141;
        n nVar26 = q141;
        n q142 = a.q1("2.5.4.24");
        P = q142;
        n nVar27 = q142;
        n q143 = a.q1("2.5.4.45");
        Q = q143;
        n nVar28 = q143;
        Hashtable hashtable = new Hashtable();
        R = hashtable;
        n nVar29 = q115;
        Hashtable hashtable2 = new Hashtable();
        S = hashtable2;
        hashtable.put(q1, "businessCategory");
        hashtable.put(q12, "c");
        hashtable.put(q13, "cn");
        hashtable.put(q14, "dc");
        hashtable.put(q15, InstabugDbContract.FeatureRequestEntry.COLUMN_DESCRIPTION);
        Object obj = InstabugDbContract.FeatureRequestEntry.COLUMN_DESCRIPTION;
        hashtable.put(q16, "destinationIndicator");
        hashtable.put(q17, "distinguishedName");
        hashtable.put(q18, "dnQualifier");
        hashtable.put(q19, "enhancedSearchGuide");
        hashtable.put(q110, "facsimileTelephoneNumber");
        hashtable.put(q111, "generationQualifier");
        hashtable.put(q112, "givenName");
        hashtable.put(q113, "houseIdentifier");
        hashtable.put(q114, "initials");
        n nVar30 = q114;
        hashtable.put(nVar29, "internationalISDNNumber");
        n nVar31 = nVar;
        hashtable.put(nVar31, "l");
        n nVar32 = nVar31;
        n nVar33 = nVar2;
        hashtable.put(nVar33, "member");
        n nVar34 = nVar33;
        n nVar35 = nVar3;
        hashtable.put(nVar35, "name");
        n nVar36 = nVar35;
        n nVar37 = nVar4;
        hashtable.put(nVar37, "o");
        n nVar38 = nVar37;
        n nVar39 = nVar5;
        hashtable.put(nVar39, "ou");
        n nVar40 = nVar39;
        n nVar41 = nVar6;
        hashtable.put(nVar41, "owner");
        n nVar42 = nVar41;
        hashtable.put(nVar7, "physicalDeliveryOfficeName");
        hashtable.put(nVar8, "postalAddress");
        hashtable.put(nVar9, "postalCode");
        hashtable.put(nVar10, "postOfficeBox");
        hashtable.put(nVar11, "preferredDeliveryMethod");
        hashtable.put(nVar12, "registeredAddress");
        hashtable.put(nVar13, "roleOccupant");
        hashtable.put(nVar14, "searchGuide");
        hashtable.put(nVar15, "seeAlso");
        hashtable.put(nVar16, "serialNumber");
        n nVar43 = nVar17;
        hashtable.put(nVar43, "sn");
        n nVar44 = nVar43;
        n nVar45 = nVar18;
        hashtable.put(nVar45, "st");
        n nVar46 = nVar45;
        n nVar47 = nVar19;
        hashtable.put(nVar47, "street");
        n nVar48 = nVar47;
        hashtable.put(nVar20, "telephoneNumber");
        hashtable.put(nVar21, "teletexTerminalIdentifier");
        hashtable.put(nVar22, "telexNumber");
        n nVar49 = nVar23;
        hashtable.put(nVar49, InstabugDbContract.FeatureRequestEntry.COLUMN_TITLE);
        Object obj2 = InstabugDbContract.FeatureRequestEntry.COLUMN_TITLE;
        n nVar50 = nVar49;
        n nVar51 = nVar24;
        hashtable.put(nVar51, "uid");
        n nVar52 = nVar51;
        hashtable.put(nVar25, "uniqueMember");
        hashtable.put(nVar26, "userPassword");
        hashtable.put(nVar27, "x121Address");
        n nVar53 = nVar28;
        hashtable.put(nVar53, "x500UniqueIdentifier");
        Hashtable hashtable3 = hashtable2;
        hashtable3.put("businesscategory", q1);
        hashtable3.put("c", q12);
        hashtable3.put("cn", q13);
        hashtable3.put("dc", q14);
        hashtable3.put(obj, q15);
        hashtable3.put("destinationindicator", q16);
        hashtable3.put("distinguishedname", q17);
        hashtable3.put("dnqualifier", q18);
        hashtable3.put("enhancedsearchguide", q19);
        hashtable3.put("facsimiletelephonenumber", q110);
        hashtable3.put("generationqualifier", q111);
        hashtable3.put("givenname", q112);
        hashtable3.put("houseidentifier", q113);
        hashtable3.put("initials", nVar30);
        hashtable3.put("internationalisdnnumber", nVar29);
        hashtable3.put("l", nVar32);
        hashtable3.put("member", nVar34);
        hashtable3.put("name", nVar36);
        hashtable3.put("o", nVar38);
        hashtable3.put("ou", nVar40);
        hashtable3.put("owner", nVar42);
        hashtable3.put("physicaldeliveryofficename", nVar7);
        hashtable3.put("postaladdress", nVar8);
        hashtable3.put("postalcode", nVar9);
        hashtable3.put("postofficebox", nVar10);
        hashtable3.put("preferreddeliverymethod", nVar11);
        hashtable3.put("registeredaddress", nVar12);
        hashtable3.put("roleoccupant", nVar13);
        hashtable3.put("searchguide", nVar14);
        hashtable3.put("seealso", nVar15);
        hashtable3.put("serialnumber", nVar16);
        hashtable3.put("sn", nVar44);
        hashtable3.put("st", nVar46);
        hashtable3.put("street", nVar48);
        hashtable3.put("telephonenumber", nVar20);
        hashtable3.put("teletexterminalidentifier", nVar21);
        hashtable3.put("telexnumber", nVar22);
        hashtable3.put(obj2, nVar50);
        hashtable3.put("uid", nVar52);
        hashtable3.put("uniquemember", nVar25);
        hashtable3.put("userpassword", nVar26);
        hashtable3.put("x121address", nVar27);
        hashtable3.put("x500uniqueidentifier", nVar53);
    }

    public b[] b(String str) {
        b[] c3 = m0.r.t.a.r.m.a1.a.c3(str, this);
        int length = c3.length;
        b[] bVarArr = new b[length];
        for (int i2 = 0; i2 != c3.length; i2++) {
            bVarArr[(length - i2) - 1] = c3[i2];
        }
        return bVarArr;
    }

    public n c(String str) {
        return m0.r.t.a.r.m.a1.a.Y0(str, this.U);
    }

    public String d(c cVar) {
        StringBuffer stringBuffer = new StringBuffer();
        b[] u2 = cVar.u();
        boolean z2 = true;
        for (int length = u2.length - 1; length >= 0; length--) {
            if (z2) {
                z2 = false;
            } else {
                stringBuffer.append(',');
            }
            m0.r.t.a.r.m.a1.a.Q(stringBuffer, u2[length], this.V);
        }
        return stringBuffer.toString();
    }

    public e f(n nVar, String str) {
        if (nVar.w(d)) {
            return new u0(str);
        }
        if (nVar.w(b) || nVar.w(E) || nVar.w(h) || nVar.w(I)) {
            return new a1(str);
        }
        return new f1(str);
    }
}
