package s0.a.a.a3;

import java.util.Objects;
import s0.a.a.n;

public interface e {
    public static final n A;
    public static final n B;
    public static final n C;
    public static final n D;
    public static final n E;
    public static final n F;
    public static final n G;
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.2.804.2.1.1.1");
        a = nVar;
        Objects.requireNonNull(nVar);
        b = new n(nVar, "1.3.1.1");
        Objects.requireNonNull(nVar);
        c = new n(nVar, "1.3.1.1.1.1");
        Objects.requireNonNull(nVar);
        d = new n(nVar, "1.2.2.1");
        Objects.requireNonNull(nVar);
        e = new n(nVar, "1.2.2.2");
        Objects.requireNonNull(nVar);
        f = new n(nVar, "1.2.2.3");
        Objects.requireNonNull(nVar);
        g = new n(nVar, "1.2.2.4");
        Objects.requireNonNull(nVar);
        h = new n(nVar, "1.2.2.5");
        Objects.requireNonNull(nVar);
        i = new n(nVar, "1.2.2.6");
        Objects.requireNonNull(nVar);
        j = new n(nVar, "1.1.3.1.1");
        Objects.requireNonNull(nVar);
        k = new n(nVar, "1.1.3.1.2");
        Objects.requireNonNull(nVar);
        l = new n(nVar, "1.1.3.1.3");
        Objects.requireNonNull(nVar);
        m = new n(nVar, "1.1.3.2.1");
        Objects.requireNonNull(nVar);
        n = new n(nVar, "1.1.3.2.2");
        Objects.requireNonNull(nVar);
        o = new n(nVar, "1.1.3.2.3");
        Objects.requireNonNull(nVar);
        p = new n(nVar, "1.1.3.3.1");
        Objects.requireNonNull(nVar);
        q = new n(nVar, "1.1.3.3.2");
        Objects.requireNonNull(nVar);
        r = new n(nVar, "1.1.3.3.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.4.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.4.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.4.3");
        Objects.requireNonNull(nVar);
        s = new n(nVar, "1.1.3.5.1");
        Objects.requireNonNull(nVar);
        t = new n(nVar, "1.1.3.5.2");
        Objects.requireNonNull(nVar);
        u = new n(nVar, "1.1.3.5.3");
        Objects.requireNonNull(nVar);
        v = new n(nVar, "1.1.3.6.1");
        Objects.requireNonNull(nVar);
        w = new n(nVar, "1.1.3.6.2");
        Objects.requireNonNull(nVar);
        x = new n(nVar, "1.1.3.6.3");
        Objects.requireNonNull(nVar);
        y = new n(nVar, "1.1.3.7.1");
        Objects.requireNonNull(nVar);
        z = new n(nVar, "1.1.3.7.2");
        Objects.requireNonNull(nVar);
        A = new n(nVar, "1.1.3.7.3");
        Objects.requireNonNull(nVar);
        B = new n(nVar, "1.1.3.8.1");
        Objects.requireNonNull(nVar);
        C = new n(nVar, "1.1.3.8.2");
        Objects.requireNonNull(nVar);
        D = new n(nVar, "1.1.3.8.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.9.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.9.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "1.1.3.9.3");
        Objects.requireNonNull(nVar);
        E = new n(nVar, "1.1.3.10.1");
        Objects.requireNonNull(nVar);
        F = new n(nVar, "1.1.3.10.2");
        Objects.requireNonNull(nVar);
        G = new n(nVar, "1.1.3.10.3");
    }
}
