package s0.a.a.s2;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface a {
    public static final n A;
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.2.410.200046");
        a = nVar;
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "1");
        b = nVar2;
        Objects.requireNonNull(nVar2);
        n nVar3 = new n(nVar2, "1");
        c = nVar3;
        Objects.requireNonNull(nVar2);
        new n(nVar2, "2");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "0");
        Objects.requireNonNull(nVar2);
        new n(nVar2, "1");
        Objects.requireNonNull(nVar3);
        d = new n(nVar3, "1");
        Objects.requireNonNull(nVar3);
        e = new n(nVar3, "2");
        Objects.requireNonNull(nVar3);
        f = new n(nVar3, "3");
        Objects.requireNonNull(nVar3);
        g = new n(nVar3, "4");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "5");
        Objects.requireNonNull(nVar3);
        h = new n(nVar3, "6");
        Objects.requireNonNull(nVar3);
        i = new n(nVar3, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar3);
        j = new n(nVar3, "8");
        Objects.requireNonNull(nVar3);
        k = new n(nVar3, "9");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "10");
        Objects.requireNonNull(nVar3);
        l = new n(nVar3, "11");
        Objects.requireNonNull(nVar3);
        m = new n(nVar3, "12");
        Objects.requireNonNull(nVar3);
        n = new n(nVar3, "13");
        Objects.requireNonNull(nVar3);
        o = new n(nVar3, "14");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "15");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "21");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "22");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "23");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "31");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "32");
        Objects.requireNonNull(nVar3);
        new n(nVar3, "33");
        Objects.requireNonNull(nVar3);
        p = new n(nVar3, "34");
        Objects.requireNonNull(nVar3);
        q = new n(nVar3, "35");
        Objects.requireNonNull(nVar3);
        r = new n(nVar3, "36");
        Objects.requireNonNull(nVar3);
        s = new n(nVar3, "37");
        Objects.requireNonNull(nVar3);
        t = new n(nVar3, "38");
        Objects.requireNonNull(nVar3);
        u = new n(nVar3, "39");
        Objects.requireNonNull(nVar3);
        v = new n(nVar3, "40");
        Objects.requireNonNull(nVar3);
        w = new n(nVar3, "41");
        Objects.requireNonNull(nVar3);
        x = new n(nVar3, "42");
        Objects.requireNonNull(nVar3);
        y = new n(nVar3, "43");
        Objects.requireNonNull(nVar3);
        z = new n(nVar3, "44");
        Objects.requireNonNull(nVar3);
        A = new n(nVar3, "45");
    }
}
