package s0.a.a.g2;

import java.util.Objects;
import s0.a.a.n;

public interface a {
    public static final n a;
    public static final n b;
    public static final n c;
    public static final n d;
    public static final n e;
    public static final n f;
    public static final n g;
    public static final n h;
    public static final n i;
    public static final n j;
    public static final n k;
    public static final n l;
    public static final n m;
    public static final n n;
    public static final n o;
    public static final n p;
    public static final n q;
    public static final n r;
    public static final n s;
    public static final n t;
    public static final n u;
    public static final n v;
    public static final n w;
    public static final n x;
    public static final n y;
    public static final n z;

    static {
        n nVar = new n("1.2.643.2.2");
        a = nVar;
        Objects.requireNonNull(nVar);
        b = new n(nVar, "9");
        Objects.requireNonNull(nVar);
        c = new n(nVar, "10");
        Objects.requireNonNull(nVar);
        d = new n(nVar, "13.0");
        Objects.requireNonNull(nVar);
        e = new n(nVar, "13.1");
        Objects.requireNonNull(nVar);
        f = new n(nVar, "21");
        Objects.requireNonNull(nVar);
        g = new n(nVar, "31.0");
        Objects.requireNonNull(nVar);
        h = new n(nVar, "31.1");
        Objects.requireNonNull(nVar);
        i = new n(nVar, "31.2");
        Objects.requireNonNull(nVar);
        j = new n(nVar, "31.3");
        Objects.requireNonNull(nVar);
        k = new n(nVar, "31.4");
        Objects.requireNonNull(nVar);
        l = new n(nVar, "20");
        Objects.requireNonNull(nVar);
        m = new n(nVar, "19");
        Objects.requireNonNull(nVar);
        n = new n(nVar, "4");
        Objects.requireNonNull(nVar);
        o = new n(nVar, "3");
        Objects.requireNonNull(nVar);
        p = new n(nVar, "30.1");
        Objects.requireNonNull(nVar);
        q = new n(nVar, "32.2");
        Objects.requireNonNull(nVar);
        r = new n(nVar, "32.3");
        Objects.requireNonNull(nVar);
        new n(nVar, "32.4");
        Objects.requireNonNull(nVar);
        new n(nVar, "32.5");
        Objects.requireNonNull(nVar);
        s = new n(nVar, "33.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "33.2");
        Objects.requireNonNull(nVar);
        new n(nVar, "33.3");
        Objects.requireNonNull(nVar);
        t = new n(nVar, "35.1");
        Objects.requireNonNull(nVar);
        u = new n(nVar, "35.2");
        Objects.requireNonNull(nVar);
        v = new n(nVar, "35.3");
        Objects.requireNonNull(nVar);
        w = new n(nVar, "36.0");
        Objects.requireNonNull(nVar);
        x = new n(nVar, "36.1");
        Objects.requireNonNull(nVar);
        new n(nVar, "36.0");
        Objects.requireNonNull(nVar);
        new n(nVar, "36.1");
        Objects.requireNonNull(nVar);
        y = new n(nVar, "96");
        Objects.requireNonNull(nVar);
        z = new n(nVar, "98");
    }
}
