package s0.a.a.d3;

import io.sentry.SentryClient;
import java.util.Objects;
import s0.a.a.n;

public interface m {
    public static final n A1;
    public static final n B1;
    public static final n C1;
    public static final n D1;
    public static final n E1;
    public static final n F1;
    public static final n G1;
    public static final n H1;
    public static final n I1;
    public static final n J1;
    public static final n K1;
    public static final n L1;
    public static final n M1;
    public static final n N1 = new n("1.2.840.10040.4.1");
    public static final n O1 = new n("1.2.840.10040.4.3");
    public static final n P1;
    public static final n Q1;
    public static final n R1;
    public static final n S1;
    public static final n T1;
    public static final n U1;
    public static final n V1;
    public static final n W1;
    public static final n X1;
    public static final n Y0;
    public static final n Z0;
    public static final n a1;
    public static final n b1;
    public static final n c1;
    public static final n d1;
    public static final n e1;
    public static final n f1;
    public static final n g1;
    public static final n h1;
    public static final n i1;
    public static final n j1;
    public static final n k1;
    public static final n l1;
    public static final n m1;
    public static final n n1;
    public static final n o1;
    public static final n p1;
    public static final n q1;
    public static final n r1;
    public static final n s1;
    public static final n t1;
    public static final n u1;
    public static final n v1;
    public static final n w1;
    public static final n x1;
    public static final n y1;
    public static final n z1;

    static {
        n nVar = new n("1.2.840.10045");
        Y0 = nVar;
        Objects.requireNonNull(nVar);
        n nVar2 = new n(nVar, "1");
        Z0 = nVar2;
        Objects.requireNonNull(nVar2);
        a1 = new n(nVar2, "1");
        Objects.requireNonNull(nVar2);
        n nVar3 = new n(nVar2, "2");
        b1 = nVar3;
        Objects.requireNonNull(nVar3);
        new n(nVar3, "3.1");
        Objects.requireNonNull(nVar3);
        c1 = new n(nVar3, "3.2");
        Objects.requireNonNull(nVar3);
        d1 = new n(nVar3, "3.3");
        Objects.requireNonNull(nVar);
        n nVar4 = new n(nVar, "4");
        e1 = nVar4;
        Objects.requireNonNull(nVar4);
        f1 = new n(nVar4, "1");
        Objects.requireNonNull(nVar);
        n nVar5 = new n(nVar, "2");
        g1 = nVar5;
        Objects.requireNonNull(nVar5);
        h1 = new n(nVar5, "1");
        Objects.requireNonNull(nVar4);
        n nVar6 = new n(nVar4, "3");
        i1 = nVar6;
        Objects.requireNonNull(nVar6);
        j1 = new n(nVar6, "1");
        Objects.requireNonNull(nVar6);
        k1 = new n(nVar6, "2");
        Objects.requireNonNull(nVar6);
        l1 = new n(nVar6, "3");
        Objects.requireNonNull(nVar6);
        m1 = new n(nVar6, "4");
        Objects.requireNonNull(nVar);
        n nVar7 = new n(nVar, "3");
        n1 = nVar7;
        Objects.requireNonNull(nVar7);
        n nVar8 = new n(nVar7, "0");
        o1 = nVar8;
        Objects.requireNonNull(nVar8);
        p1 = new n(nVar8, "1");
        Objects.requireNonNull(nVar8);
        q1 = new n(nVar8, "2");
        Objects.requireNonNull(nVar8);
        r1 = new n(nVar8, "3");
        Objects.requireNonNull(nVar8);
        s1 = new n(nVar8, "4");
        Objects.requireNonNull(nVar8);
        t1 = new n(nVar8, "5");
        Objects.requireNonNull(nVar8);
        u1 = new n(nVar8, "6");
        Objects.requireNonNull(nVar8);
        v1 = new n(nVar8, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar8);
        new n(nVar8, "8");
        Objects.requireNonNull(nVar8);
        new n(nVar8, "9");
        Objects.requireNonNull(nVar8);
        w1 = new n(nVar8, "10");
        Objects.requireNonNull(nVar8);
        x1 = new n(nVar8, "11");
        Objects.requireNonNull(nVar8);
        y1 = new n(nVar8, "12");
        Objects.requireNonNull(nVar8);
        z1 = new n(nVar8, "13");
        Objects.requireNonNull(nVar8);
        new n(nVar8, "14");
        Objects.requireNonNull(nVar8);
        new n(nVar8, "15");
        Objects.requireNonNull(nVar8);
        A1 = new n(nVar8, "16");
        Objects.requireNonNull(nVar8);
        B1 = new n(nVar8, "17");
        Objects.requireNonNull(nVar8);
        C1 = new n(nVar8, "18");
        Objects.requireNonNull(nVar8);
        D1 = new n(nVar8, "19");
        Objects.requireNonNull(nVar8);
        E1 = new n(nVar8, "20");
        Objects.requireNonNull(nVar7);
        n nVar9 = new n(nVar7, "1");
        F1 = nVar9;
        Objects.requireNonNull(nVar9);
        G1 = new n(nVar9, "1");
        Objects.requireNonNull(nVar9);
        H1 = new n(nVar9, "2");
        Objects.requireNonNull(nVar9);
        I1 = new n(nVar9, "3");
        Objects.requireNonNull(nVar9);
        J1 = new n(nVar9, "4");
        Objects.requireNonNull(nVar9);
        K1 = new n(nVar9, "5");
        Objects.requireNonNull(nVar9);
        L1 = new n(nVar9, "6");
        Objects.requireNonNull(nVar9);
        M1 = new n(nVar9, SentryClient.SENTRY_PROTOCOL_VERSION);
        n nVar10 = new n("1.3.133.16.840.63.0");
        P1 = nVar10;
        Objects.requireNonNull(nVar10);
        Q1 = new n(nVar10, "2");
        Objects.requireNonNull(nVar10);
        R1 = new n(nVar10, "3");
        Objects.requireNonNull(nVar10);
        S1 = new n(nVar10, "16");
        n nVar11 = new n("1.2.840.10046");
        T1 = nVar11;
        Objects.requireNonNull(nVar11);
        U1 = new n(nVar11, "2.1");
        Objects.requireNonNull(nVar11);
        n nVar12 = new n(nVar11, "3");
        V1 = nVar12;
        Objects.requireNonNull(nVar12);
        new n(nVar12, "1");
        Objects.requireNonNull(nVar12);
        new n(nVar12, "2");
        Objects.requireNonNull(nVar12);
        new n(nVar12, "3");
        Objects.requireNonNull(nVar12);
        new n(nVar12, "4");
        Objects.requireNonNull(nVar12);
        new n(nVar12, "5");
        Objects.requireNonNull(nVar12);
        new n(nVar12, "6");
        Objects.requireNonNull(nVar12);
        new n(nVar12, SentryClient.SENTRY_PROTOCOL_VERSION);
        Objects.requireNonNull(nVar12);
        new n(nVar12, "8");
        n nVar13 = new n("1.3.133.16.840.9.44");
        W1 = nVar13;
        Objects.requireNonNull(nVar13);
        n nVar14 = new n(nVar13, "1");
        X1 = nVar14;
        Objects.requireNonNull(nVar14);
        new n(nVar14, "1");
        Objects.requireNonNull(nVar14);
        new n(nVar14, "2");
    }
}
